// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DBEntities))]
    [Migration("20210812135108_ModifiedCustomerAndSupplierModels")]
    partial class ModifiedCustomerAndSupplierModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.Bill", b =>
                {
                    b.Property<Guid>("BillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("BillID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("UserID");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoryImagePath")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CategoryName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Models.Feature", b =>
                {
                    b.Property<Guid>("FeatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeatureName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FeatureNameAr")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MenuIcon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("FeatureID");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            FeatureID = new Guid("6899c2c5-5860-4994-a7e2-d061aed3e0c4"),
                            FeatureName = "Security",
                            FeatureNameAr = "نظام الحماية",
                            MenuIcon = "icon-wrench"
                        },
                        new
                        {
                            FeatureID = new Guid("5e3d5747-9a45-4541-86ad-03c5bc659714"),
                            FeatureName = "Control Panel",
                            FeatureNameAr = "لوحة التحكم",
                            MenuIcon = "icon-settings"
                        });
                });

            modelBuilder.Entity("Models.Item", b =>
                {
                    b.Property<Guid>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BillID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("char(36)");

                    b.HasKey("ItemID");

                    b.HasIndex("BillID");

                    b.HasIndex("ProductID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Models.NotificationAction", b =>
                {
                    b.Property<Guid>("NotificationActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("TitleEn")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("NotificationActionID");

                    b.ToTable("NotificationActions");

                    b.HasData(
                        new
                        {
                            NotificationActionID = new Guid("0160f613-f583-4a5f-a15a-4461afaef8be"),
                            ActionName = "ForgetPassword",
                            TitleEn = "Forget password"
                        },
                        new
                        {
                            NotificationActionID = new Guid("ceb98ab9-8390-4ebb-999d-be6de77b21c6"),
                            ActionName = "VerifyUser",
                            TitleEn = "Verify user"
                        });
                });

            modelBuilder.Entity("Models.NotificationSetting", b =>
                {
                    b.Property<Guid>("NotificationSettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NotificationActionID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NotificationTypeID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TemplateName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("NotificationSettingID");

                    b.HasIndex("NotificationActionID");

                    b.HasIndex("NotificationTypeID");

                    b.ToTable("NotificationSettings");

                    b.HasData(
                        new
                        {
                            NotificationSettingID = new Guid("46d44ee1-f477-435f-b0b2-87ae3b80b6d0"),
                            NotificationActionID = new Guid("0160f613-f583-4a5f-a15a-4461afaef8be"),
                            NotificationTypeID = new Guid("c8d58b31-3fa8-44ab-b24f-fa85ad33c954"),
                            Subject = "Change password",
                            TemplateName = "ForgetPassword"
                        },
                        new
                        {
                            NotificationSettingID = new Guid("a1c8df0c-ccfa-4e41-889a-8851247c2fd0"),
                            NotificationActionID = new Guid("ceb98ab9-8390-4ebb-999d-be6de77b21c6"),
                            NotificationTypeID = new Guid("c8d58b31-3fa8-44ab-b24f-fa85ad33c954"),
                            Subject = "Verify user",
                            TemplateName = "verification"
                        },
                        new
                        {
                            NotificationSettingID = new Guid("672cf768-aff5-41fd-84c4-2d0b8fa81996"),
                            NotificationActionID = new Guid("ceb98ab9-8390-4ebb-999d-be6de77b21c6"),
                            NotificationTypeID = new Guid("f5702875-5374-4b55-87dd-3da62895f6fb"),
                            Subject = "Verify user",
                            TemplateName = "verificationSMS"
                        });
                });

            modelBuilder.Entity("Models.NotificationType", b =>
                {
                    b.Property<Guid>("NotificationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("TypeName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("NotificationTypeID");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            NotificationTypeID = new Guid("c8d58b31-3fa8-44ab-b24f-fa85ad33c954"),
                            TypeName = "Email"
                        },
                        new
                        {
                            NotificationTypeID = new Guid("f5702875-5374-4b55-87dd-3da62895f6fb"),
                            TypeName = "SMS"
                        },
                        new
                        {
                            NotificationTypeID = new Guid("c74cedbf-53bc-4020-b168-46bd6fde0ddf"),
                            TypeName = "InAppNotification"
                        });
                });

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ProductDetails")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProductImagePath")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierID")
                        .HasColumnType("char(36)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Models.PurchaseOrder", b =>
                {
                    b.Property<Guid>("PurchaseOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PurchasedQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierID")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("PurchaseOrderID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SupplierID");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Models.Right", b =>
                {
                    b.Property<Guid>("RightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FeatureID")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MenuIcon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("RightCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RightName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RightNameAr")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("RightOrder")
                        .HasColumnType("int");

                    b.Property<string>("RightURL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("RightID");

                    b.HasIndex("FeatureID");

                    b.ToTable("Rights");

                    b.HasData(
                        new
                        {
                            RightID = new Guid("4edc50ca-a7c0-4278-8930-707ec2e5919c"),
                            FeatureID = new Guid("6899c2c5-5860-4994-a7e2-d061aed3e0c4"),
                            IsVisible = true,
                            MenuIcon = "icon-docs",
                            RightCode = "roles",
                            RightName = "Manage Roles",
                            RightNameAr = "ادارة الادوار",
                            RightOrder = 1,
                            RightURL = "#/pages/roles"
                        },
                        new
                        {
                            RightID = new Guid("78831e46-adab-41ed-a9de-4d5229ccb15f"),
                            FeatureID = new Guid("6899c2c5-5860-4994-a7e2-d061aed3e0c4"),
                            IsVisible = true,
                            MenuIcon = "icon-users",
                            RightCode = "users",
                            RightName = "Manage Users",
                            RightNameAr = "ادارة المستخدمين",
                            RightOrder = 2,
                            RightURL = "#/pages/users"
                        });
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsSystemRole")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("RoleName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleNameAr")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = new Guid("7232fe79-deab-41dc-a54d-f83d388d4f09"),
                            IsSystemRole = true,
                            RoleName = "admin"
                        });
                });

            modelBuilder.Entity("Models.RoleRight", b =>
                {
                    b.Property<Guid>("RoleRightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RightID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("char(36)");

                    b.HasKey("RoleRightID");

                    b.HasIndex("RightID");

                    b.HasIndex("RoleID");

                    b.ToTable("RoleRights");

                    b.HasData(
                        new
                        {
                            RoleRightID = new Guid("0de0622b-97db-4edd-acfa-a5adeb81673b"),
                            RightID = new Guid("4edc50ca-a7c0-4278-8930-707ec2e5919c"),
                            RoleID = new Guid("7232fe79-deab-41dc-a54d-f83d388d4f09")
                        },
                        new
                        {
                            RoleRightID = new Guid("8ac6ded6-4c93-4d95-8396-b526925d322d"),
                            RightID = new Guid("78831e46-adab-41ed-a9de-4d5229ccb15f"),
                            RoleID = new Guid("7232fe79-deab-41dc-a54d-f83d388d4f09")
                        });
                });

            modelBuilder.Entity("Models.Sale", b =>
                {
                    b.Property<Guid>("SaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BillID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("int");

                    b.HasKey("SaleID");

                    b.HasIndex("BillID");

                    b.HasIndex("ProductID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Models.Supplier", b =>
                {
                    b.Property<Guid>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("SupplierEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SupplierName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SupplierPhone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssociatedCompanyID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("d1364e8b-58e2-423b-a048-03ffd7ef6253"),
                            FullName = " Admin",
                            IsActive = true,
                            RoleID = new Guid("7232fe79-deab-41dc-a54d-f83d388d4f09"),
                            UserEmail = "admin@admin.com",
                            UserName = "admin",
                            UserPassword = "ꉟ뺾"
                        });
                });

            modelBuilder.Entity("Models.Bill", b =>
                {
                    b.HasOne("Models.Customer", "Customer")
                        .WithMany("BillList")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Models.Item", b =>
                {
                    b.HasOne("Models.Bill", "Bill")
                        .WithMany("ItemList")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.Product", "Product")
                        .WithMany("ItemList")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Models.NotificationSetting", b =>
                {
                    b.HasOne("Models.NotificationAction", "NotificationAction")
                        .WithMany("NotificationSettings")
                        .HasForeignKey("NotificationActionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.HasOne("Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.Supplier", "Supplier")
                        .WithMany("SuppliedProducts")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Models.PurchaseOrder", b =>
                {
                    b.HasOne("Models.Product", "Product")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Models.Right", b =>
                {
                    b.HasOne("Models.Feature", "Feature")
                        .WithMany("Rights")
                        .HasForeignKey("FeatureID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Models.RoleRight", b =>
                {
                    b.HasOne("Models.Right", "Right")
                        .WithMany("RoleRights")
                        .HasForeignKey("RightID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.Role", "Role")
                        .WithMany("RoleRights")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Models.Sale", b =>
                {
                    b.HasOne("Models.Bill", "Bill")
                        .WithMany("Sales")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.Product", "Product")
                        .WithMany("ProductSales")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.HasOne("Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
